plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
# default front-matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: GCCR
      permalink: /news/:year/:month/:day/:title
      type: NewsArticle
  - scope:
      path: ""
    values:
      layout: "default"
      type: Organization
      image: /assets/img/logo_400x400.jpg
  - scope:
      path: "assets/"
    values:
      sitemap: false
# blog pages
paginate: 5
paginate_path: "/news/page:num/"
# google analytics
google_analytics: UA-162429198-1
# seo
title: Global Consortium for Chemosensory Research (GCCR)
description: Website of the Global Consortium for Chemosensory Research (GCCR)
url: https://gcchemosensr.org/
lang: en_US
logo: /assets/img/logo_32x32.jpg
author: GCCR
twitter:
  username: GCChemosensoryR
  card: summary
facebook:
  publisher: https://www.facebook.com/GCChemosensoryR/
social:
  name: Global Consortium for Chemosensory Research
  links:
    - https://twitter.com/GCChemosensoryR
    - https://github.com/GCCR
    - https://www.facebook.com/GCChemosensoryR/