name: gccr
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.*
  - google-api-python-client==2.49.*
  - pandas==1.4.*
  - geopandas==0.10.*
  - yaml==0.2.*
  - bokeh==2.4.*
  - seaborn
  - pyzotero==1.5.*
  - ca-certificates
  - openssl
  - selenium
  - certifi
  - openpyxl
  - pip:
    - geckodriver-autoinstaller==0.1.0
