name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  github-pages:

    runs-on: ubuntu-18.04

    steps:
    - name: Install dependencies for the members map
      run: |
        sudo apt-get update -y
        sudo apt-get install -y firefox
    - name: Clone GitHub repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r _scripts/requirements.txt
    - name: Run Zotero script
      env:
        ZOTERO_KEY: ${{ secrets.ZOTERO_KEY }}
      run: python _scripts/zotero_to_yml.py
    - name: Build members map and list
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      run: |
        mkdir -p assets/data
        python _scripts/make_members_data.py
    - name: Build committees section
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        COMMITTEES_SPREADSHEET_ID: ${{ secrets.COMMITTEES_SPREADSHEET_ID }}
      run: python _scripts/make_committees_data.py
    - name: Build and deploy
      uses: helaili/jekyll-action@2.0.1
      env:
        JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}