name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  github-pages:

    runs-on: ubuntu-18.04

    steps:
    - name: Install dependencies for the members map
      run: |
        sudo apt-get update -y
        sudo apt-get install -y firefox

    - name: Clone GitHub repo
      uses: actions/checkout@v2

    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: _scripts/environment.yml
        environment-name: gccr
        cache-env: true

    - name: Run Zotero script
      env:
        ZOTERO_KEY: ${{ secrets.ZOTERO_KEY }}
      run: python _scripts/zotero_to_yml.py

    - name: Build members map and list
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        MEMBERS_SPREADSHEET_ID: ${{ secrets.MEMBERS_SPREADSHEET_ID }}
      run: |
        mkdir -p assets/data
        python _scripts/make_members_data.py

    - name: Build committees section
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        COMMITTEES_SPREADSHEET_ID: ${{ secrets.COMMITTEES_SPREADSHEET_ID }}
      run: python _scripts/make_committees_data.py

    - name: Build and deploy
      uses: helaili/jekyll-action@v2
      with:
        target_branch: 'gh-pages'
        token: ${{ secrets.JEKYLL_PAT }}
